; Listing generated by Microsoft (R) Optimizing Compiler Version 19.11.25508.2 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	arith
; Function compile flags: /Odtp
; File f:\csapp\ca3\pa_3.20.c
_TEXT	SEGMENT
x$ = 8
arith	PROC

; 3    : {

	mov	DWORD PTR [rsp+8], ecx

; 4    : 	return x OP 8;

	mov	eax, DWORD PTR x$[rsp]
	cdq
	and	edx, 7
	add	eax, edx
	sar	eax, 3

; 5    : }

	ret	0
arith	ENDP
_TEXT	ENDS
END
